"""UserIdentityMiddleware — reads users/{user_id}/identity.md.

Position 7 in chain. Injects identity file content if it exists,
otherwise injects an empty block. Identity file is generated by
the offline pipeline after 10+ sessions.
"""

from __future__ import annotations

from pathlib import Path

from langchain_core.runnables import RunnableConfig

from app.sophia_agent.state import SophiaState


class UserIdentityMiddleware:
    """Inject user identity file into system prompt."""

    runs_during_crisis = False

    def __init__(self, user_id: str):
        self._user_id = user_id

    async def before(self, state: SophiaState, config: RunnableConfig) -> SophiaState:
        if state.get("skip_expensive"):
            return state
        identity_path = Path(f"users/{self._user_id}/identity.md")
        if identity_path.exists():
            content = identity_path.read_text()
            state.setdefault("system_prompt_blocks", []).append(content)
        state["user_id"] = self._user_id
        return state
