import { useCallback, useEffect, useRef } from 'react';

import { getSessionMessages, isError } from '../lib/api/sessions-api';
import {
  hasRenderableAssistantText,
  normalizeAssistantTextForDedupe,
} from '../lib/assistant-message-dedupe';
import { debugLog } from '../lib/debug-logger';
import { recordSophiaCaptureEvent } from '../lib/session-capture';
import type { BuilderCompletionEventV1 } from '../types/builder-completion';

type MessagePart = { type?: string; text?: string };

type ChatMessageLike = {
  id: string;
  role: string;
  parts: MessagePart[];
};

type AppendableChatMessage = {
  id: string;
  role: 'user' | 'assistant';
  parts: Array<{ type: 'text'; text: string }>;
};

type BackfillReason = 'stream-missing-final' | 'builder-completion';

type BackfillOutcome =
  | 'appended'
  | 'replaced'
  | 'dedupe-suppressed'
  | 'no-candidate'
  | 'skipped'
  | 'error';

interface UseSessionAssistantReplyBackfillParams {
  enabled: boolean;
  backendSessionId?: string;
  userId?: string;
  chatMessages: ChatMessageLike[];
  chatStatus: 'submitted' | 'streaming' | 'ready' | 'error';
  builderCompletion: BuilderCompletionEventV1 | null;
  setChatMessages: (
    updater: (prev: AppendableChatMessage[]) => AppendableChatMessage[]
  ) => void;
  setMessageTimestamp: (id: string, createdAt: string) => void;
}

/** Delays (ms) for re-checking thread state after a stream turn that ended
 * with no visible assistant text. The final AIMessage may have been written
 * to LangGraph state without ever being token-streamed (observed with the
 * OpenAI companion fallback). */
const STREAM_BACKFILL_DELAYS_MS = [1_500, 6_000];

/** Delays (ms) after a builder terminal event. The companion "wakeup" run
 * that announces the artifact is a gateway-dispatched background run with no
 * browser stream consumer — its reply lands in thread state several seconds
 * after the terminal webhook. */
const BUILDER_BACKFILL_DELAYS_MS = [4_000, 9_000, 16_000];

function messageText(message: ChatMessageLike): string {
  return (message.parts || [])
    .filter((part) => part?.type === 'text' && typeof part.text === 'string')
    .map((part) => part.text ?? '')
    .join('');
}

function builderCompletionKey(event: BuilderCompletionEventV1 | null): string | null {
  if (!event?.task_id) return null;
  return `${event.task_id}:${event.run_id ?? ''}`;
}

function visibleAssistantTextCoversCandidate(visibleText: string, candidateText: string): boolean {
  const visible = normalizeAssistantTextForDedupe(visibleText);
  const candidate = normalizeAssistantTextForDedupe(candidateText);
  return Boolean(visible && candidate && (visible === candidate || visible.includes(candidate)));
}

function candidateExtendsVisibleAssistantText(visibleText: string, candidateText: string): boolean {
  const visible = normalizeAssistantTextForDedupe(visibleText);
  const candidate = normalizeAssistantTextForDedupe(candidateText);
  return Boolean(visible && candidate && candidate.length > visible.length && candidate.includes(visible));
}

/**
 * Recovers final assistant replies that exist in the session's durable
 * transcript / LangGraph thread state but were never appended by the live
 * stream. Two triggers:
 *
 * 1. A chat stream turn finishes without having appended any new visible
 *    assistant text (the run succeeded but the final AIMessage was not
 *    token-streamed).
 * 2. A builder completion arrives — the companion wakeup acknowledgment is
 *    generated by a background run the browser never streams.
 *
 * Strictly additive and deduplicated: only the conversation's FINAL message
 * is ever considered, only when it is an assistant message with visible
 * text, and never when the same id or normalized text is already on screen.
 * Tool-call-only turns yield no candidate (the gateway endpoint filters
 * empty assistant messages), so no fake reply is ever synthesized.
 */
export function useSessionAssistantReplyBackfill({
  enabled,
  backendSessionId,
  userId,
  chatMessages,
  chatStatus,
  builderCompletion,
  setChatMessages,
  setMessageTimestamp,
}: UseSessionAssistantReplyBackfillParams) {
  const chatMessagesRef = useRef(chatMessages);
  chatMessagesRef.current = chatMessages;
  const chatStatusRef = useRef(chatStatus);
  chatStatusRef.current = chatStatus;

  const timersRef = useRef<Set<ReturnType<typeof setTimeout>>>(new Set());
  const appendedIdsRef = useRef<Set<string>>(new Set());
  const inFlightRef = useRef(false);
  const wasStreamingRef = useRef(false);
  const assistantTextCountAtTurnStartRef = useRef(0);
  const lastBuilderCompletionKeyRef = useRef<string | null>(null);
  /** Generation token — bumping it invalidates all scheduled attempts. */
  const scheduleGenerationRef = useRef(0);

  const countVisibleAssistantTexts = useCallback(() => (
    chatMessagesRef.current.filter(
      (message) => message.role === 'assistant' && hasRenderableAssistantText(messageText(message)),
    ).length
  ), []);

  const clearScheduledAttempts = useCallback(() => {
    scheduleGenerationRef.current += 1;
    for (const timer of timersRef.current) {
      clearTimeout(timer);
    }
    timersRef.current.clear();
  }, []);

  const recordOutcome = useCallback((reason: BackfillReason, outcome: BackfillOutcome) => {
    recordSophiaCaptureEvent({
      category: 'companion',
      name: 'assistant-reply-backfill',
      payload: {
        reason,
        assistantMessageBackfillResult: outcome,
        assistantMessageStreamSeen: outcome !== 'appended',
        assistantMessageFinalStateRecovered: outcome === 'appended',
        assistantMessageDedupeSuppressed: outcome === 'dedupe-suppressed',
        assistantMessageVisibleCount: countVisibleAssistantTexts(),
        rawProviderPayloadExcluded: true,
        providerSecretsExcluded: true,
      },
    });
  }, [countVisibleAssistantTexts]);

  const runBackfillOnce = useCallback(async (reason: BackfillReason): Promise<BackfillOutcome> => {
    if (!enabled || !backendSessionId || !userId) {
      return 'skipped';
    }
    const status = chatStatusRef.current;
    if (status === 'streaming' || status === 'submitted') {
      // A new turn is in flight — its stream owns the message list now.
      return 'skipped';
    }
    if (inFlightRef.current) {
      return 'skipped';
    }

    inFlightRef.current = true;
    try {
      const result = await getSessionMessages(backendSessionId, userId);
      if (isError(result)) {
        debugLog('AssistantReplyBackfill', 'transcript fetch failed', {
          status: result.status,
          reason,
        });
        recordOutcome(reason, 'error');
        return 'error';
      }

      const transcript = Array.isArray(result.data.messages) ? result.data.messages : [];
      const finalMessage = transcript[transcript.length - 1];
      // Only the conversation's final message qualifies: appending an older
      // mid-history assistant message at the end would reorder the chat.
      if (finalMessage?.role !== 'sophia') {
        recordOutcome(reason, 'no-candidate');
        return 'no-candidate';
      }

      const candidateContent = finalMessage.content || '';
      if (!hasRenderableAssistantText(candidateContent)) {
        recordOutcome(reason, 'no-candidate');
        return 'no-candidate';
      }

      const candidateId = finalMessage.id || `backfill-${backendSessionId}-${transcript.length}`;
      if (appendedIdsRef.current.has(candidateId)) {
        recordOutcome(reason, 'dedupe-suppressed');
        return 'dedupe-suppressed';
      }

      const replacementTarget = chatMessagesRef.current.find((message) => (
        message.role === 'assistant'
        && candidateExtendsVisibleAssistantText(messageText(message), candidateContent)
      ));
      const isVisibleEquivalent = (message: ChatMessageLike) => (
        message.role === 'assistant'
        && !candidateExtendsVisibleAssistantText(messageText(message), candidateContent)
        && (message.id === candidateId || visibleAssistantTextCoversCandidate(messageText(message), candidateContent))
      );
      if (chatMessagesRef.current.some(isVisibleEquivalent)) {
        appendedIdsRef.current.add(candidateId);
        recordOutcome(reason, 'dedupe-suppressed');
        return 'dedupe-suppressed';
      }

      appendedIdsRef.current.add(candidateId);
      const createdAt = finalMessage.created_at || new Date().toISOString();
      setMessageTimestamp(replacementTarget?.id ?? candidateId, createdAt);
      if (replacementTarget) {
        setChatMessages((prev) => prev.map((message) => (
          message.id === replacementTarget.id
            ? {
              ...message,
              parts: [{ type: 'text' as const, text: candidateContent }],
            }
            : message
        )));
        debugLog('AssistantReplyBackfill', 'replaced partial assistant reply', {
          reason,
          candidateIdPresent: Boolean(finalMessage.id),
          contentLength: normalizeAssistantTextForDedupe(candidateContent).length,
        });
        recordOutcome(reason, 'replaced');
        return 'replaced';
      }

      setChatMessages((prev) => {
        if (prev.some(isVisibleEquivalent)) {
          return prev;
        }
        return [
          ...prev,
          {
            id: candidateId,
            role: 'assistant' as const,
            parts: [{ type: 'text' as const, text: candidateContent }],
          },
        ];
      });

      debugLog('AssistantReplyBackfill', 'appended missed assistant reply', {
        reason,
        candidateIdPresent: Boolean(finalMessage.id),
        contentLength: normalizeAssistantTextForDedupe(candidateContent).length,
      });
      recordOutcome(reason, 'appended');
      return 'appended';
    } catch {
      recordOutcome(reason, 'error');
      return 'error';
    } finally {
      inFlightRef.current = false;
    }
  }, [backendSessionId, enabled, recordOutcome, setChatMessages, setMessageTimestamp, userId]);

  const scheduleBackfill = useCallback((reason: BackfillReason, delays: readonly number[]) => {
    if (!enabled || !backendSessionId || !userId) {
      return;
    }
    const generation = scheduleGenerationRef.current;
    for (const delay of delays) {
      const timer = setTimeout(() => {
        timersRef.current.delete(timer);
        if (generation !== scheduleGenerationRef.current) {
          return;
        }
        void runBackfillOnce(reason).then((outcome) => {
          // Once resolved (appended or already visible), later retries for
          // this batch are unnecessary — invalidate them.
          if (outcome === 'appended' || outcome === 'replaced' || outcome === 'dedupe-suppressed') {
            clearScheduledAttempts();
          }
        });
      }, delay);
      timersRef.current.add(timer);
    }
  }, [backendSessionId, clearScheduledAttempts, enabled, runBackfillOnce, userId]);

  // Trigger 1 — a stream turn finished but appended no new assistant text.
  useEffect(() => {
    const isStreaming = chatStatus === 'streaming' || chatStatus === 'submitted';
    if (isStreaming && !wasStreamingRef.current) {
      assistantTextCountAtTurnStartRef.current = countVisibleAssistantTexts();
    }
    if (!isStreaming && wasStreamingRef.current && chatStatus === 'ready') {
      const appendedDuringTurn =
        countVisibleAssistantTexts() > assistantTextCountAtTurnStartRef.current;
      if (!appendedDuringTurn) {
        scheduleBackfill('stream-missing-final', STREAM_BACKFILL_DELAYS_MS);
      }
    }
    wasStreamingRef.current = isStreaming;
  }, [chatStatus, countVisibleAssistantTexts, scheduleBackfill]);

  // Trigger 2 — a builder completion arrived; the companion wakeup reply
  // lands in thread state shortly after with no stream consumer.
  useEffect(() => {
    const key = builderCompletionKey(builderCompletion);
    if (!key || key === lastBuilderCompletionKeyRef.current) {
      return;
    }
    lastBuilderCompletionKeyRef.current = key;
    scheduleBackfill('builder-completion', BUILDER_BACKFILL_DELAYS_MS);
  }, [builderCompletion, scheduleBackfill]);

  // Reset on session change / unmount.
  useEffect(() => {
    appendedIdsRef.current.clear();
    lastBuilderCompletionKeyRef.current = null;
    return () => {
      clearScheduledAttempts();
    };
  }, [backendSessionId, clearScheduledAttempts]);
}
