"""Identity file management — users/{user_id}/identity.md.

Generated by offline pipeline step 6 every 10 sessions or on
structural memory change. Read by UserIdentityMiddleware.
"""

from __future__ import annotations

from pathlib import Path

IDENTITY_PROMPT = Path(__file__).parent / "prompts" / "identity_file_update.md"


def get_session_count(user_id: str) -> int:
    """Count sessions from trace files."""
    traces_dir = Path(f"users/{user_id}/traces")
    if not traces_dir.exists():
        return 0
    return len(list(traces_dir.glob("*.json")))


def should_update_identity(user_id: str, session_count: int) -> bool:
    """Trigger identity update every 10 sessions or on structural memory change."""
    return session_count > 0 and session_count % 10 == 0


async def update_identity_file(user_id: str) -> None:
    """Regenerate users/{user_id}/identity.md from Mem0 data via Claude Haiku."""
    # TODO(jorge): Implement identity generation
    pass
