"""Deterministic schemas and policy for the one-repair deck design-lift loop."""

from deerflow.sophia.deck_design_lift.comparator import compare_deck_versions
from deerflow.sophia.deck_design_lift.compiler import (
    RepairProgramRejected,
    compile_repair_program,
    validate_candidate_against_program,
)
from deerflow.sophia.deck_design_lift.repair_executor import (
    AsyncImmutableObjectStore,
    DeckRepairAuthor,
    DeckRepairInvokeOnceError,
    DurableDeckRepairExecutor,
    RepairInvocationObjectPaths,
    repair_invocation_object_paths,
)
from deerflow.sophia.deck_design_lift.runtime import (
    AtomicDeckManifestCommitter,
    BlindDeckJudgmentRequest,
    DeckCandidateMaterializer,
    DeckDesignLiftRequest,
    DeckDesignLiftResult,
    DeckDesignLiftRuntime,
    DeckDesignLiftRuntimeError,
    DeckMechanics,
    DeckQualityJudge,
    DeckRepairExecutor,
    InitialRenderedJudgment,
    RepairInvocationRequest,
    RuntimeDisposition,
    RuntimeTerminalCode,
    StagedDeckCandidate,
)
from deerflow.sophia.deck_design_lift.schemas import (
    AssetUpdate,
    ContentPreservationProof,
    DeckRepairCandidate,
    DeckRepairProgram,
    DeckVersionComparison,
    DeckVersionComparisonInput,
    JudgmentRepairFinding,
    LocalityProof,
    RepairCompilerInput,
    RepairRenderEvidence,
    SelectorRepair,
    SelectorSourceAuthorization,
    SkillRef,
    SourceUpdate,
    VersionCriterionScore,
    VersionQualityEvidence,
)

__all__ = [
    "AssetUpdate",
    "AtomicDeckManifestCommitter",
    "AsyncImmutableObjectStore",
    "BlindDeckJudgmentRequest",
    "ContentPreservationProof",
    "DeckCandidateMaterializer",
    "DeckDesignLiftRequest",
    "DeckDesignLiftResult",
    "DeckDesignLiftRuntime",
    "DeckDesignLiftRuntimeError",
    "DeckMechanics",
    "DeckQualityJudge",
    "DeckRepairCandidate",
    "DeckRepairAuthor",
    "DeckRepairExecutor",
    "DeckRepairInvokeOnceError",
    "DeckRepairProgram",
    "DeckVersionComparison",
    "DeckVersionComparisonInput",
    "JudgmentRepairFinding",
    "InitialRenderedJudgment",
    "LocalityProof",
    "RepairCompilerInput",
    "RepairInvocationRequest",
    "RepairInvocationObjectPaths",
    "RepairProgramRejected",
    "RepairRenderEvidence",
    "SelectorRepair",
    "SelectorSourceAuthorization",
    "SkillRef",
    "SourceUpdate",
    "RuntimeDisposition",
    "RuntimeTerminalCode",
    "StagedDeckCandidate",
    "VersionCriterionScore",
    "VersionQualityEvidence",
    "compare_deck_versions",
    "compile_repair_program",
    "repair_invocation_object_paths",
    "validate_candidate_against_program",
    "DurableDeckRepairExecutor",
]
